/**
 * Permission constants generated from `permissions_list.json`.
 *
 * Only permissions present in `permissions_list.json` are included here.
 * Keys are derived from the human-friendly `name` field in the JSON,
 * converted to UPPER_SNAKE_CASE and stripped of special characters.
 *
 * If you need to look up a permission by code, use the permissionGroupCode value (e.g. "PERM-003").
 */
export const PERMISSION_IDS = {
  // Generated from permissions_list.json
  CREATE_SINGLE_USER: 'PERM-001',
  BULK_IMPORT_USERS: 'PERM-002',
  VIEW_ALL_USERS: 'PERM-003',
  VIEW_USER_DETAILS: 'PERM-004',
  UPDATE_USER: 'PERM-005',
  DISABLE_ENABLE_USER: 'PERM-006',
  CREATE_ROLE: 'PERM-007',
  VIEW_ALL_ROLES: 'PERM-008',
  UPDATE_ROLE: 'PERM-009',
  DISABLE_ENABLE_ROLE: 'PERM-010',
  CREATE_DEPARTMENT: 'PERM-011',
  VIEW_ALL_DEPARTMENTS: 'PERM-012',
  VIEW_DEPARTMENT_DETAILS: 'PERM-013',
  UPDATE_DEPARTMENT: 'PERM-014',
  DISABLE_ENABLE_DEPARTMENT: 'PERM-015',
  CREATE_COURSE: 'PERM-016',
  VIEW_ALL_COURSES: 'PERM-017',
  VIEW_COURSE_DETAILS: 'PERM-018',
  UPDATE_COURSE: 'PERM-019',
  ARCHIVE_COURSE: 'PERM-020',
  ASSIGN_TRAINERS: 'PERM-021',
  REMOVE_TRAINERS: 'PERM-022',
  CREATE_BULK_SUBJECTS: 'PERM-023',
  CREATE_SUBJECT: 'PERM-024',
  VIEW_ALL_SUBJECTS: 'PERM-025',
  VIEW_SUBJECT_DETAILS: 'PERM-026',
  UPDATE_SUBJECT: 'PERM-027',
  ARCHIVE_SUBJECT: 'PERM-028',
  BULK_ENROLL_TRAINEES: 'PERM-029',
  ENROLL_SINGLE_TRAINEE: 'PERM-030',
  VIEW_ALL_ENROLLMENTS: 'PERM-031',
  REMOVE_TRAINEE_FROM_ENROLLMENT: 'PERM-032',
  CREATE_TEMPLATE: 'PERM-033',
  EDIT_DRAFT_TEMPLATE: 'PERM-034',
  SUBMIT_TEMPLATE_FOR_APPROVAL: 'PERM-035',
  DELETE_DRAFT_TEMPLATE: 'PERM-036',
  UPDATE_TEMPLATE_VERSION: 'PERM-037',
  UPDATE_TEMPLATE_STATUS: 'PERM-038',
  APPROVE_DENY_TEMPLATE: 'PERM-039',
  VIEW_ALL_TEMPLATE: 'PERM-040',
  VIEW_TEMPLATE_DETAILS: 'PERM-041',
  DOWNLOAD_TEMPLATE_AS_PDF: 'PERM-042',
  VIEW_ALL_INCIDENT_FEEDBACK_REPORT: 'PERM-043',
  VIEW_INCIDENT_FEEDBACK_REPORT_DETAILS: 'PERM-044',
  VIEW_SUBMITTED_REPORTS: 'PERM-045',
  SUBMIT_INCIDENT_FEEDBACK_REPORT: 'PERM-046',
  CANCEL_INCIDENT_FEEDBACK_REPORT: 'PERM-047',
  ACKNOWLEDGE_INCIDENT_REPORTS: 'PERM-048',
  RESOLVE_INCIDENT_FEEDBACK_REPORTS: 'PERM-049',
  CREATE_GLOBAL_FIELD: 'PERM-050',
  VIEW_ALL_GLOBAL_FIELDS: 'PERM-051',
  VIEW_GLOBAL_FIELD_DETAILS: 'PERM-052',
  UPDATE_GLOBAL_FIELD: 'PERM-053',
  DISABLE_ENABLE_GLOBAL_FIELD: 'PERM-054'
};

// NOTE: The previous file contained additional constants that referenced
// permission codes not present in `permissions_list.json`. Those keys were
// intentionally removed here so this file only reflects the canonical list.
